TBR tools/runutil: using Setpgid instead of Setsid to fix breakage of the 'git veyron review' tool:
ERROR: 'git commit --allow-empty -e -m ...'
emacs: Could not open file: /dev/tty
error: There was a problem with the editor 'emacs'.
Please supply the message using either -m or -F option.

Change-Id: I79a46217cfb135bd77b212b2503503508df645d1