tools/lib/git: making sure "git diff" does not fail on HUGE changelists
I just saw "git veyron review" fail on very large changelists with the error:
ERROR: 'git diff cleanse..cleanse-REVIEW' failed:

I suspect it is because the changelist is too big and its contents
overflows a buffer that git uses to let you scroll through the diff
output. Adding "--no-pager" option disables scrolling and fixes this
issue.

Change-Id: Ib16db061e97ad2892b9e7b2a4033950911ae2398