tools/{lib,veyron}: propagating errors across processes
During my veyron development presentation, it was suggested we add a
"-n" option to the veyron tools that only prints the commands that it
is about to execute, but does not execute them. I looked into this
feature request and identified two issues with this:

1) In some cases the tools can fail because of a call to the Go
standard library os package function fails. It seems excessive to wrap
all calls to the os package functions.

2) In some cases the behavior of the tool depends on the output of the
command to be run. In other words, deciding which commands need to be
run even if the "-n" option is provided and which don't, requires
understanding of the program logic.

After considering these two issues, I have decided to address the
problem that the "-n" option tries to address -- debugging of the tool
failing -- in a different way: this CL propagates error messages
across process, resulting in more informative messages.

For instance:

PREVIOUSLY:
>> Updating tool "veyron"
>>>> veyron -v=false project update tools
>>>> FAILED
>> FAILED
ERROR: command failed

NOW:
>> Updating tool "veyron"
>>>> veyron -v=false project update tools
>>>> FAILED
>> FAILED
ERROR: ERROR: Chdir(/Users/jsimsa/veyron/.manifest) failed: chdir /Users/jsimsa/veyron/.manifest: no such file or directory

PREVIOUSLY:
>> Updating tool "veyron"
>>>> veyron -v=false update tools
>>>> FAILED
>> FAILED
ERROR: command failed

NOW:
>> Updating tool "veyron"
>>>> veyron -v=false update tools
>>>> FAILED
>> FAILED
ERROR: ERROR: veyron: unknown command "update"
...

PREVIOUSLY:
>> Updating tool "veyron"
>>>> veyron -v=false project update tools
>>>>>> update project tools in "/Users/jsimsa/veyron/tools"
>>>>>> OK
>>>> OK
>>>> /Users/jsimsa/veyron/veyron/scripts/build/go buid -ldflags -X tools/veyron/impl.commitId 70 -o /Users/jsimsa/veyron/bin/veyron tools/veyron
>>>> FAILED
>> FAILED
ERROR: command failed

NOW:
>> Updating tool "veyron"
>>>> veyron -v=false project update tools
>>>>>> update project tools in "/Users/jsimsa/veyron/tools"
>>>>>> OK
>>>> OK
>>>> /Users/jsimsa/veyron/veyron/scripts/build/go buid -ldflags -X tools/veyron/impl.commitId 70 -o /Users/jsimsa/veyron/bin/veyron tools/veyron
>>>> FAILED
>> FAILED
ERROR: veyron tool update failed
go: unknown subcommand "buid"
Run 'go help' for usage.

Change-Id: Ifbf77c2df74e6cee91bc68262b231e5728db2cce